"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { BarChart3, LogOut, User } from "lucide-react"
import { Button } from "@/components/ui/button"
import { ActivityPanel } from "@/components/activity-panel"
import { ActivityManager } from "@/components/activity-manager"
import { AgeStatistics } from "@/components/age-statistics"
import { createClient } from "@/lib/supabase/client"
import { parseActivityRow, parseParticipantRow, type Activity, type Participant } from "@/lib/types"
import type { User as SupabaseUser } from "@supabase/supabase-js"

type Tab = string | "estatisticas"
export default function Home() {
  const supabase = createClient(); const router = useRouter()
  const [user, setUser] = useState<SupabaseUser | null>(null); const [activities, setActivities] = useState<Activity[]>([]); const [participants, setParticipants] = useState<Participant[]>([]); const [tab, setTab] = useState<Tab>("estatisticas"); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  const activeActivity = useMemo(() => activities.find((activity) => activity.id === tab), [activities, tab])
  useEffect(() => { async function load() { const { data: { user } } = await supabase.auth.getUser(); setUser(user); if (!user) { router.replace("/auth/login"); return } const [activityResult, participantResult] = await Promise.all([supabase.from("activities").select("*").eq("user_id", user.id).order("created_at"), supabase.from("participants").select("*").eq("user_id", user.id).order("time")]); if (activityResult.error) setError(activityResult.error.message); else setActivities((activityResult.data ?? []).map(parseActivityRow)); if (participantResult.error) setError(participantResult.error.message); else setParticipants((participantResult.data ?? []).map(parseParticipantRow)); setLoading(false) } void load() }, [router, supabase])
  const createActivity = useCallback(async (data: any) => { if (!user) return; const { data: row, error: requestError } = await supabase.from("activities").insert({ user_id: user.id, name: data.name, description: data.description, icon: data.icon, measurement_type: data.measurementType }).select().single(); if (requestError) { setError(requestError.message); return } setActivities((items) => [...items, parseActivityRow(row)]) }, [supabase, user])
  const updateActivity = useCallback(async (id: string, data: any) => { const { data: row, error: requestError } = await supabase.from("activities").update({ name: data.name, description: data.description, icon: data.icon, measurement_type: data.measurementType }).eq("id", id).eq("user_id", user?.id ?? "").select().single(); if (requestError) { setError(requestError.message); return } setActivities((items) => items.map((item) => item.id === id ? parseActivityRow(row) : item)) }, [supabase, user])
  const deleteActivity = useCallback(async (id: string) => { const { error: requestError } = await supabase.from("activities").delete().eq("id", id).eq("user_id", user?.id ?? ""); if (requestError) { setError("Não foi possível excluir uma brincadeira com participantes vinculados."); return } setActivities((items) => items.filter((item) => item.id !== id)); if (tab === id) setTab("estatisticas") }, [supabase, tab, user])
  const addParticipant = useCallback(async (participant: Participant) => { if (!user) return; const { data, error: requestError } = await supabase.from("participants").insert({ user_id: user.id, name: participant.name, age: participant.age, time: participant.time, activity: participant.activity, activity_id: participant.activityId }).select().single(); if (requestError) { setError(requestError.message); return } setParticipants((items) => [...items, parseParticipantRow(data)]) }, [supabase, user])
  const removeParticipant = useCallback(async (id: string) => { const { error: requestError } = await supabase.from("participants").delete().eq("id", id).eq("user_id", user?.id ?? ""); if (requestError) setError(requestError.message); else setParticipants((items) => items.filter((item) => item.id !== id)) }, [supabase, user])
  if (loading) return <main className="flex min-h-screen items-center justify-center bg-background"><p className="text-muted-foreground">Carregando...</p></main>
  return <main className="min-h-screen bg-background"><header className="sticky top-0 z-50 border-b border-border bg-card/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-primary text-sm font-bold text-primary-foreground">PI</div><div><h1 className="font-bold">Projeto Integrador</h1><p className="text-xs text-muted-foreground">Registro de atividades</p></div></div><div className="flex items-center gap-3 text-sm text-muted-foreground"><span className="hidden truncate md:inline">{user?.email}</span><User className="size-4" /><Button variant="ghost" size="sm" onClick={async () => { await supabase.auth.signOut(); router.push("/auth/login"); router.refresh() }}><LogOut data-icon="inline-start" /><span className="sr-only">Sair</span></Button></div></div></header><div className="mx-auto flex max-w-6xl flex-col gap-6 px-4 py-6">{error && <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<ActivityManager activities={activities} onCreate={createActivity} onUpdate={updateActivity} onDelete={deleteActivity} /><nav className="flex gap-2 overflow-x-auto rounded-xl border border-border bg-secondary p-1.5"><Button variant={tab === "estatisticas" ? "default" : "ghost"} onClick={() => setTab("estatisticas")}><BarChart3 data-icon="inline-start" />Estatísticas</Button>{activities.map((activity) => <Button key={activity.id} variant={tab === activity.id ? "default" : "ghost"} onClick={() => setTab(activity.id)}>{activity.name}</Button>)}</nav>{activeActivity && <ActivityPanel activity={activeActivity} participants={participants.filter((item) => item.activityId === activeActivity.id || (!item.activityId && item.activity === activeActivity.name))} onAdd={addParticipant} onRemove={removeParticipant} />}{tab === "estatisticas" && <section className="rounded-xl border border-border bg-card p-6"><div className="mb-6"><h2 className="text-xl font-bold">Estatísticas por faixa etária</h2><p className="text-sm text-muted-foreground">Distribuição dos participantes em cada atividade.</p></div><AgeStatistics activities={activities} participants={participants} /></section>}</div></main>
}
