"use client"

import { Button } from "@/components/ui/button"
import { Trash2, Trophy } from "lucide-react"
import type { Participant } from "@/lib/types"
import { formatTime } from "@/lib/types"

interface Props { participants: Participant[]; onRemove: (id: string) => Promise<void> }
export function ParticipantsTable({ participants, onRemove }: Props) { const sorted = [...participants].sort((a, b) => a.time - b.time); if (!sorted.length) return <div className="py-12 text-center text-sm text-muted-foreground">Nenhum participante registrado ainda.</div>; return <div className="overflow-hidden rounded-lg border border-border"><table className="w-full text-sm"><thead><tr className="border-b border-border bg-secondary/50"><th className="px-3 py-2.5 text-left text-xs text-muted-foreground">#</th><th className="px-3 py-2.5 text-left text-xs text-muted-foreground">Nome</th><th className="px-3 py-2.5 text-left text-xs text-muted-foreground">Idade</th><th className="px-3 py-2.5 text-left text-xs text-muted-foreground">Tempo</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{sorted.map((participant, index) => <tr key={participant.id} className="border-b border-border last:border-b-0"><td className="px-3 py-2.5 font-mono text-muted-foreground">{index === 0 && sorted.length > 1 ? <Trophy className="size-4 text-accent" aria-label="Primeiro lugar" /> : index + 1}</td><td className="px-3 py-2.5 font-medium">{participant.name}</td><td className="px-3 py-2.5">{participant.age} anos</td><td className="px-3 py-2.5 font-mono font-semibold text-primary">{formatTime(participant.time)}</td><td className="px-3 py-2.5"><Button variant="ghost" size="sm" onClick={() => void onRemove(participant.id)} className="text-destructive"><Trash2 data-icon="inline-start" /><span className="sr-only">Remover</span></Button></td></tr>)}</tbody></table></div> }
